### ISSUE TITLE
模型效果有点奇怪

### ISSUE THREAD

**Issue by oysz2016** [AirBernard/Scene-Text-Detection-with-SPCNET#14]
用ICDAR2015和ICDAR2017数据训练了下，测试的时候发现效果非常差是什么原因？

**Comment by simplify23** [comment]
你好，可以分享一下你的预训练模型吗，我的邮箱956491659@qq.com

**Comment by xtg88** [comment]
我训练出来的效果也很差，只用了水平方向文本训练，测试也是用水平方向的文字测试。但是效果很差，我拿训练的数据去测试，效果还是很差，不知道是什么原因
